services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: vpp_db
      POSTGRES_USER: vpp_user
      POSTGRES_PASSWORD: vpp_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  virtual_power_grid_system_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: virtual_power_grid_system_service
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: default

volumes:
  postgres_data:
  redis_data: