spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vpp_db
    username: vpp_user
    password: vpp_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      INDENT_OUTPUT: true

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080