CREATE TABLE battery
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255) NOT NULL,
    postcode      INT          NOT NULL,
    watt_capacity BIGINT       NOT NULL
);